const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('alwaysHere', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  setClickThrough: (ignore) => ipcRenderer.invoke('set-click-through', ignore),
  getScreenSize: () => ipcRenderer.invoke('get-screen-size'),
  setAutoStart: (enable) => ipcRenderer.invoke('set-auto-start', enable),
  getAutoStart: () => ipcRenderer.invoke('get-auto-start'),
  listPets: () => ipcRenderer.invoke('list-pets'),
  getPetSpritesheet: (petId) => ipcRenderer.invoke('get-pet-spritesheet', petId),
  choosePetFolder: () => ipcRenderer.invoke('choose-pet-folder'),
  importPetPackage: () => ipcRenderer.invoke('import-pet-package'),
  openExternal: (url) => ipcRenderer.invoke('open-external-url', url),
  exportActivityLog: (csvText) => ipcRenderer.invoke('export-activity-log', csvText),
  showNotification: (payload) => ipcRenderer.invoke('show-notification', payload),
  onShowSettings: (callback) => ipcRenderer.on('show-settings', callback),
  onTrayCommand: (callback) => ipcRenderer.on('tray-command', (_event, command) => callback(command)),
  fetchHolidays: (year) => ipcRenderer.invoke('fetch-holidays', year),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkHotUpdate: () => ipcRenderer.invoke('check-hot-update'),
  resetConfig: () => ipcRenderer.invoke('reset-config'),
  openPetFolder: (petId) => ipcRenderer.invoke('open-pet-folder', petId),
  deletePet: (petId) => ipcRenderer.invoke('delete-pet', petId),
  // ── 语音 / 小智对话 ──
  voiceConnect: () => ipcRenderer.invoke('voice-connect'),
  voiceDisconnect: () => ipcRenderer.invoke('voice-disconnect'),
  voiceSendText: (text) => ipcRenderer.invoke('voice-send-text', text),
  voiceSendSystemText: (text) => ipcRenderer.invoke('voice-send-system-text', text),
  voiceAbort: () => ipcRenderer.invoke('voice-abort'),
  voiceStatus: () => ipcRenderer.invoke('voice-status'),
  voiceAsr: (wavBuffer) => ipcRenderer.invoke('voice-asr', wavBuffer),
  voiceReregisterShortcut: () => ipcRenderer.invoke('voice-reregister-shortcut'),
  getConversationHistory: (options) => ipcRenderer.invoke('conversation-history', options),
  summarizeConversation: (options) => ipcRenderer.invoke('conversation-summary', options),
  // ── 看屏幕说话(视觉) ──
  visionLookAndSay: () => ipcRenderer.invoke('vision-look-and-say'),
  visionStartLoop: (seconds) => ipcRenderer.invoke('vision-start-loop', seconds),
  visionStopLoop: () => ipcRenderer.invoke('vision-stop-loop'),
  onVoiceEvent: (callback) => ipcRenderer.on('voice-event', (_event, data) => callback(data))
})
